#!/bin/bash
for num_hashes in {5..100..5}
do
	for hash_range in {16..27}
	do
		for multiplicity in {1..5}
		do
			../../build/runme ../../data/rockyou/rockyou-data-small ../../data/rockyou/rockyou-queries 13 1 $num_hashes $hash_range $multiplicity
 		done
	done
done
