#!/bin/bash
# Run with e.g. ./run-rockyou-trials ../output/rockyou-trials
for num_hashes in {5..100..5}
do
	for hash_range in {16..27}
	do
		for multiplicity in {1..5}
		do
			../build/runme ../data/rockyou/data ../data/rockyou/queries 3 1 $num_hashes $hash_range $multiplicity 3
 		done
	done
done
