#!/bin/bash
# Run with e.g. ./run-sift-trials ../output/sift-results
for num_hashes in {20..100..20}
do
	for hash_range in 20, 22, 24
	do
		for multiplicity in 4, 8, 16, 32
		do
      for r in 400
      do
			  ../build/runme ../data/sift/data ../data/sift/queries 2 2 $num_hashes $hash_range $multiplicity $r
      done
 		done
	done
done
