#!/bin/bash

# Rockyou is complete

# Sift
cd sift
wget ftp://ftp.irisa.fr/local/texmex/corpus/sift.tar.gz
tar -xf sift.tar.gz 
cd ..
mv sift/sift/* sift/
rmdir sift/sift
python split.py
rm sift/*.fvecs
rm sift/*.ivecs
rm sift/sift.tar.gz
